version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: spends_tracker_backend
    ports:
      - '3031:8000'
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/spends_tracker.db
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - /mnt/ironwolf8tb/spends:/app/data # Custom path for persistent data
    restart: unless-stopped
